/**
 * Copyright (c) 2017, UCLA Software Engineering and Analysis Laboratory (SEAL)
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * The views and conclusions contained in the software and documentation are those
 * of the authors and should not be interpreted as representing official policies,
 * either expressed or implied, of the FreeBSD Project.
 */
package edu.utexas.seal.plugins.database;

import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import org.eclipse.core.resources.IWorkspace;
import org.eclipse.core.resources.ResourcesPlugin;
import org.hsqldb.server.Server;

import edu.utexas.seal.plugins.edit.UTAbstractEdit;

/**
 * @author troy
 * 
 */
public class UTCriticsDBServer {
	Connection		con;
	Server			server;
	private String	leftContextName;
	private String	rightContextName;
	private String	diffsName;

	public void start() {
		IWorkspace workspace = ResourcesPlugin.getWorkspace();
		String path = workspace.getRoot().getLocation().toString();
		path = "file:" + path + "/diffDB/diffDB";

		server = new Server();
		server.setAddress("localhost");
		server.setDatabaseName(0, "diffDB");
		server.setDatabasePath(0, path);
		server.setPort(9010);
		server.setTrace(true);
		server.setLogWriter(new PrintWriter(System.out));
		server.start();
		try {
			Class.forName("org.hsqldb.jdbc.JDBCDriver");
		} catch (ClassNotFoundException e) {
			System.out.println("ERROR: failed to load HSQLDB JDBC driver.");
			e.printStackTrace(System.out);
		}
	}

	public Connection connect() {
		try {
			con = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost:9010/diffDB", "SA", "");
		} catch (SQLException e) {
			System.out.println("ERROR: failed to connect to DB server.");
			e.printStackTrace();
		}

		return con;
	}

	/**
	 * Used to create tables, including diffs table, old context table and new context table
	 * It is called each time comparing two projects
	 * 
	 * @param name1
	 * @param name2
	 */
	public void createTables(String name1, String name2) {
		leftContextName = "left" + "_" + name1 + "_" + name2;
		String leftContextTableS = "create table " + leftContextName +
		// "( id int generated by default as identity(START WITH 1  INCREMENT BY 1), " +
				"( id int, " + "context clob, " + "Primary Key(id) )";

		rightContextName = "right" + "_" + name1 + "_" + name2;
		String rightContextTableS = "create table " + rightContextName +
		// "( id int generated by default as identity(START WITH 1  INCREMENT BY 1), " +
				"( id int, " + "context clob, " + "Primary Key(id) )";

		diffsName = "diffs" + "_" + name1 + "_" + name2;
		String diffsTableS = "create table "
				+ diffsName
				// "( id int generated by default as identity(START WITH 1  INCREMENT BY 1), " +
				+ "( id int, " + "type varchar(50), " + "leftStart int, " + "leftEnd int, " + "rightStart int, " + "rightEnd int, " + "leftS clob, " + "rightS clob, "
				+ "leftC int, " + "rightC int, " + "leftFile varchar(256), " + "rightFile varchar(256), " + "Primary Key(id), " + "Foreign Key(leftC) references "
				+ leftContextName + "(id), " + "Foreign Key(leftC) references " + rightContextName + "(id) )";
		try {
			con.createStatement().executeUpdate(leftContextTableS);
			con.createStatement().executeUpdate(rightContextTableS);
			con.createStatement().executeUpdate(diffsTableS);
		} catch (SQLException e) {
			System.out.println("ERROR: failed to create tables.");
			e.printStackTrace();
		}
	}

	public void insertNewContext(UTAbstractEdit edit) {
		String newContext;
		if (edit.getLeftEditContext() == null) {
			newContext = "null";
		} else {
			newContext = edit.getLeftEditContext();
		}

		String insert = "insert into " + leftContextName + "(id, context) " + "values(" + "'" + edit.getEditId() + "'," + "'" + newContext + "')";

		try {
			con.createStatement().execute(insert);
		} catch (SQLException e) {
			System.out.println("ERROR: failed to insert new contexts.");
			e.printStackTrace();
		}
	}

	public void insertOldContext(UTAbstractEdit edit) {
		String oldContext;
		if (edit.getRightEditContext() == null) {
			oldContext = "null";
		} else {
			oldContext = edit.getRightEditContext();
		}

		String insert = "insert into " + rightContextName + "(id, context) " + "values(" + "'" + edit.getEditId() + "'," + "'" + oldContext + "')";
		try {
			con.createStatement().execute(insert);
		} catch (SQLException e) {
			System.out.println("ERROR: failed to insert old contexts.");
			e.printStackTrace();
		}
	}

	public void insertEdit(UTAbstractEdit edit, String leftFile, String rightFile) {
		String insert = "insert into " + diffsName + "(id, type, leftStart, leftEnd, rightStart, rightEnd, leftS, rightS, leftC, rightC, leftFile, rightFile) "
				+ "values(" + "'" + edit.getEditId() + "'," + "'" + edit.getEditKind() + "'," + "'" + edit.getLeftEditOffsetBgn() + "'," + "'"
				+ edit.getLeftEditOffsetEnd() + "'," + "'" + edit.getRightEditOffsetEnd() + "'," + "'" + edit.getRightEditOffsetEnd() + "'," + "'"
				+ edit.getLeftEditStatement() + "'," + "'" + edit.getRightEditStatement() + "'," + "'" + edit.getEditId() + "'," + "'" + edit.getEditId() + "'," + "'"
				+ leftFile + "'," + "'" + rightFile + "')";
		try {
			con.createStatement().execute(insert);
		} catch (SQLException e) {
			System.out.println("ERROR: failed to insert edits.");
			e.printStackTrace();
		}
	}

	public void disconnect() {
		try {
			con.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		try {
			con.isClosed();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
